# https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:
  api:
    depends_on:
      - es
      - metadata
    image: dnresearch/appbadservice
    ports:
      - "8080:80"
    restart: "on-failure"
    environment:
      - METADATA_CONNECTION=server=metadata;port=3306;database=abad;uid=appbad_user;password='';
    networks:
      - front-tier
      - back-tier
  kibana:
    depends_on:
      - es
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    networks:
      - front-tier
      - back-tier
    volumes:
       - ./kibana.yml:/usr/share/kibana/config/kibana.yml
       - kibanadata:/usr/share/kibana/data
  metadata:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dnpw12
    volumes: 
      - metadata:/var/lib/mysql
      - ./scripts/create-db-user.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - back-tier
  
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - back-tier      
volumes:
  esdata:
    driver: local    
  kibanadata:
    driver: local
  metadata:
    driver: local

networks:
  front-tier: {}
  back-tier: {}