apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "appbad.fullname" . }}
  labels:
    {{- include "appbad.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appbad.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "appbad.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appbad.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: MYSQL_HOST
            value: {{ .Values.mysql.host }}
          - name: MYSQL_PORT
            value: {{ .Values.mysql.port }}
          - name: MYSQL_DATABASE
            value: {{ .Values.mysql.database }}
{{- if .Values.mysql.credsecret }}             
          - name: MYSQL_USER 
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.credsecret }}
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.credsecret }}
                key: password                
{{- else }}
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: ""
{{- end }}            
          - name: ES_ADDRESS
            value: {{ .Values.elasticsearch.address }}
{{- if .Values.elasticsearch.credsecret }}                            
          - name: ES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.elasticsearch.credsecret }}
                key: username   
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.elasticsearch.credsecret }}
                key: password
{{- end }}
          - name: ES_INDEX_SUFFIX
            value: {{ .Values.elasticsearch.indexSuffix }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 4                        
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 2              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
